name: Build MolCompassKnimeNode

on:
  workflow_dispatch:
    inputs:
      knime_version:
        description: 'KNIME Version'
        required: true
        default: '4.7'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        knime_version: ['5.2'] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: 3.8

      - name: Install knime-extension-bundling
        run: |
          conda create -n knime-ext-bundling -c knime -c conda-forge knime-extension-bundling=${{ matrix.knime_version }} ensureconda=1.4.3
          conda activate knime-ext-bundling
        shell: bash -l {0}

      - name: Run build_python_extension script for KNIME ${{ matrix.knime_version }}
        run: |
          conda activate knime-ext-bundling
          build_python_extension.py molcompass molcompass_build_${{ matrix.knime_version }}
        shell: bash -l {0}

      - name: Zip the results
        run: zip -r molcompass_build_${{ matrix.knime_version }}.zip molcompass_build_${{ matrix.knime_version }}

      - name: Upload the zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: molcompass_build_${{ matrix.knime_version }}_artifact
          path: molcompass_build_${{ matrix.knime_version }}.zip
